version: '3'

volumes:
  meetupsdb:
    driver: local

services:

  app:
    container_name: app-meetups
    build:
        context: .
        dockerfile: docker/app/Dockerfile
        args:
          requirements: /app/docker/app/requirements/dev.txt
    depends_on:
      - db
    env_file:
      - "docker/app/.env"
    command: "/app/scripts/start-reload.sh"
    ports:
      - "5000:${PORT:-5000}"
      - "8001:8001"
    volumes:
      - ".:/app"

  db:
    container_name: db-meetups
    build: docker/sql
    env_file: docker/sql/.env
    ports:
      - "5433:5432"
    volumes:
      - meetupsdb:/var/lib/postgresql/data/